[package]
name = "bioimg_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { workspace = true }
ndarray-npy = { workspace = true }
paste = "1.0.14"
thiserror = "1.0.57"
bioimg_spec = { path = "../bioimg_spec" }
image.workspace = true
