on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-binary:
    name: build-binary ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            artifact: bioimg_gui.exe
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
            os: ubuntu-latest
            artifact: bioimg_gui
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact: bioimg_gui
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact: bioimg_gui
    steps:
      - uses: actions/checkout@v4
      - name: install linux deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release --package bioimg_gui
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bioimg_gui-${{ matrix.target }}_latest.zip
          path: |
            target/${{ matrix.target }}/release/${{ matrix.artifact }}
